### Get all users
GET http://localhost:3001/users
Accept: application/json


### Get a single user by ID
GET http://localhost:3001/users/687017cc5b08bed1da2bb7ee
Accept: application/json

### Create a new user
POST http://localhost:3001/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@example.com",
  "favoriteColor": "blue",
  "birthday": "1990-01-01"
}


### Update an existing user by ID
PUT http://localhost:3001/users/
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "favoriteColor": "green",
  "birthday": "1992-03-15"
}

### Delete a user by ID
DELETE http://localhost:3001/users/

